name: "Features Integration Tests"
on: [push, pull_request]

jobs:
  features-test:
    uses: temporalio/features/.github/workflows/java.yaml@WorkflowUpdateHandle # TODO: switch back to `main`
    with:
      java-repo-path: ${{github.event.pull_request.head.repo.full_name}}
      version: ${{github.event.pull_request.head.ref}}
      version-is-repo-ref: true